# Generated by Django 6.0.3 on 2026-04-14 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=100)),
                ('disciplina_curso', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professor')),
            ],
            options={
                'unique_together': {('aluno', 'professor')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='professores',
            field=models.ManyToManyField(related_name='alunos', through='accounts.Matricula', to='accounts.professor'),
        ),
    ]
