# Generated by Django 6.0.3 on 2026-04-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOMINIO', 'Domínio Total'), ('PRATICA', 'Mão na Massa'), ('EVOLUCAO', 'Evolução Constante')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_medalhas', to='accounts.aluno')),
            ],
        ),
    ]
