# Generated by Django 6.0.3 on 2026-04-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('questoes', models.TextField(blank=True, null=True, verbose_name='Questões da Lição')),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licoes', to='accounts.professor')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, verbose_name='Resposta do Aluno')),
                ('codigo_enviado', models.TextField(blank=True, verbose_name='Código/Script')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Professor')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_entregas', to='accounts.aluno')),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='courses.licao')),
            ],
            options={
                'unique_together': {('licao', 'aluno')},
            },
        ),
    ]
