# Generated by Django 6.0.3 on 2026-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_entrega_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-data_entrega'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterUniqueTogether(
            name='entrega',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entrega',
            name='tentativa_numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Tentativa Nº'),
        ),
    ]
