# Generated by Django 6.0.3 on 2026-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='licao',
            name='questoes',
            field=models.TextField(blank=True, null=True, verbose_name='Questões da Lição'),
        ),
    ]
