# Generated by Django 6.0.3 on 2026-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_entrega_options_alter_entrega_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='xp',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
