# Generated by Django 6.0.3 on 2026-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_entrega_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='codigo_enviado',
        ),
        migrations.AddField(
            model_name='entrega',
            name='acertou',
            field=models.BooleanField(default=False, verbose_name='O aluno acertou?'),
        ),
    ]
